### PR TITLE
Add GLES Support and initial Rockchip platform

### PR DESCRIPTION
**Pull request by mrfixit2001**

### CODE REVIEW

**Comment by inactive123** [comment]
Interesting, does it actually work with GLES?

**Comment by mrfixit2001** [comment]
Yes, quite well actually :) I will be uploading a test release of recalbox with mainline for rockchip soon if you’d like to test it. 

Side note - the same exact patch can apply to both vitavoyager and vitaquake3 makefile, but neither will compile for GLES. There’s other q3 repos that have been ported to GLES so those commits will need to be ported to support it.

**Comment by Rinnegatamante** [comment]
Adapting idtech3 code to work with GLES shouldn't be too problematic. Do you have a compilation output pointing out the issues?

**Comment by mrfixit2001** [comment]
At the moment both vitaquake3 and vitavoyager insist on including gl.h, which doesn’t exist for GLES. I’m sure more compile issues will surface once that’s fixed. But it’s the first failure. 

Vitaquake2 compiles and works fine.

**Comment by mrfixit2001** [comment]
Regarding vitaquake3 and GLES... Perhaps this commit is a good place to start:
https://github.com/twolife/ioq3/commit/f17e19e3c7d3483d7b780085a2eed175f81bd01f

And as reference, the following repo should support GLES and is fairly recently updated:
https://github.com/cdev-tux/q3lite

Lastly - OpenArena has the same back-end as Q3 and would be awesome to have ported as well. The following repo should support GLES, and may also help for reference when adding GLES support to Q3:
https://github.com/ptitSeb/OpenArenaPandora

**Comment by Rinnegatamante** [comment]
vitaQuakeIII core already supports Quake III: Arena, Quake III: Team Arena, OpenArena, Q3Rally and Urban Terror.

**Comment by mrfixit2001** [comment]
Awesome! Just need to add GLES support and I'll be all over it :D

**Pull request merged**
